### ISSUE TITLE
i can't call demo method，it report: System.AccessViolationException

### ISSUE THREAD

**Issue by Charltsing** [trungnt2910/MemoryModule.NET#36]
project(vs2022 ,net framework 4.72)
[demo.zip](https://github.com/trungnt2910/MemoryModule.NET/files/11608578/demo.zip)

![捕获](https://github.com/trungnt2910/MemoryModule.NET/assets/19963715/8817e42b-d8cc-48d7-87a7-45daa2b4783c)

Did I make any mistake?

**Comment by trungnt2910** [comment]
Which version of the library are you using? The prerelease versions have known problems.

**Comment by trungnt2910** [comment]
The latest version has bugs (#34)

You might want to use MemoryModule.NET version 0.1.0 on NuGet instead.

**Comment by Charltsing** [comment]
> The latest version has bugs (#34)
> 
> You might want to use MemoryModule.NET version 0.1.0 on NuGet instead.

i try 0.1.0, but it has the same problem

maybe someting is wrong?

**Comment by Charltsing** [comment]
https://github.com/wwh1004/MemoryModule,
[MemoryModuleLite](https://github.com/wwh1004/MemoryModule/tree/master/MemoryModuleLite)

it works fine

**Comment by trungnt2910** [comment]
It seems like my implementation is getting the wrong address, off by 0x10000 bytes.

I am looking into this, haven't touched this code for quite a long time.

**Comment by trungnt2910** [comment]
Your example works fine on my new branch (https://github.com/trungnt2910/MemoryModule.NET/tree/dev/trungnt2910/Abstractions), where I wrote the PE loader from scratch.

My old branch was ported from the old MemoryModule C code, and to be honest I don't really understand what it is. The new one was created from scratch using a new design.

The only problem preventing this branch to be merged into master is #34. The approach of hooking TLS functions seems to not work on Windows since Windows does not have a dedicated function for TLS handling, instead Windows applications directly access the segment registers FS and GS.

I do not currently have much time to work on this project, but I would be grateful if you have any suggestions on how to fix this particular issue on the master branch.

**Comment by Charltsing** [comment]
I hope to load dll with minimal code, [MemoryModuleLite](https://github.com/wwh1004/MemoryModule/tree/master/MemoryModuleLite) looks good

**Comment by Charltsing** [comment]
https://github.com/bb107/MemoryModulePP/blob/master/MemoryModule/MmpTls.cpp

**Comment by trungnt2910** [comment]
Sorry for the delay, but this issue should be fixed in the latest version. Please check the NuGet library for the latest review.
